# Generated by Django 4.0.3 on 2022-03-23 00:10

import django.contrib.postgres.fields
import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=32),
                blank=True,
                default=movies.models.get_default_roles,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="file_path",
            field=models.FileField(
                blank=True, upload_to="film_works", verbose_name="Файл"
            ),
        ),
    ]
